name: Achievements
on:
    # Schedule updates (each hour)
    schedule: [{ cron: '0 * * * *' }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ['output'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update metrics'
                  filename: metrics.plugin.achievements.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: ''
                  plugin_achievements: yes
                  plugin_achievements_only: >-
                      polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
                      scripter, packager, explorer, infographile, manager
                  plugin_achievements_threshold: X
