name: Recent activity charts
on:
    # Schedule updates (every 6 hours)
    schedule:
        - cron: '0 */8 * * *'
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ['output'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update metrics'
                  filename: metrics.plugin.habits.charts.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: ''
                  plugin_habits: yes
                  plugin_habits_facts: no
                  plugin_habits_charts: yes
                  config_timezone: America/Detroit
