name: isocalendar
on:
    # Schedule updates (each hour)
    schedule: [{ cron: '0 * * * *' }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ['output'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@v3.28
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update metrics'
                  filename: metrics.plugin.isocalendar.halfyear.svg
                  base: ''
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: half-year
                  token: ${{ secrets.GITHUB_TOKEN }}
