name: Metrics
on:
    # Schedule updates (each hour)
    schedule: [{ cron: '0 * * * *' }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ['main'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  #   output_action: commit
                  #   committer_branch: output
                  #   committer_message: 'update metrics'
                  # Your GitHub token
                  # The following scopes are required:
                  #  - public_access (default scope)
                  # The following additional scopes may be required:
                  #  - read:org      (for organization related metrics)
                  #  - read:user     (for user related data)
                  #  - read:packages (for some packages related data)
                  #  - repo          (optional, if you want to include private repositories)
                  token: ${{ secrets.GITHUB_TOKEN }}

                  # Options
                  user: minhtran241
                  template: classic
                  base: header, activity, community, repositories, metadata
                  base_hireable: yes
                  base_indepth: yes
                  config_display: large
                  config_octicon: yes
                  config_padding: 0, 2 + 2%
                  config_timezone: America/Detroit
                  config_twemoji: yes
                  plugin_achievements: yes
                  plugin_achievements_display: detailed
                  plugin_achievements_secrets: yes
                  plugin_achievements_threshold: C
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: half-year
                  plugin_languages: yes
                  plugin_languages_analysis_timeout: 15
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_details: bytes-size, percentage
                  plugin_languages_ignored: html,css,pug
                  plugin_languages_limit: 8
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%

            - uses: Platane/snk@master
              id: snake-gif

              with:
                  github_user_name: minhtran241
                  svg_out_path: dist/github-contribution-grid-snake.svg
            - uses: crazy-max/ghaction-github-pages@v2.1.3
              with:
                  target_branch: output
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: lowlighter/metrics@latest
              with:
                  filename: metrics.plugin.lines.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: repositories
                  plugin_lines: yes

            - uses: lowlighter/metrics@latest
              with:
                  filename: metrics.plugin.habits.charts.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: ''
                  plugin_habits: yes
                  plugin_habits_facts: no
                  plugin_habits_charts: yes
                  config_timezone: America/Detroit

            - uses: lowlighter/metrics@latest
              with:
                  filename: metrics.plugin.licenses.ratio.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: ''
                  template: repository
                  repo: metrics
                  plugin_licenses: yes
                  plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
                  plugin_licenses_legal: no
                  plugin_licenses_ratio: yes

            - uses: lowlighter/metrics@latest
              with:
                  filename: metrics.plugin.languages.recent.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: ''
                  plugin_languages: yes
                  plugin_languages_ignored: >-
                      html, css, pug, less, dockerfile, makefile, qmake, lex, cmake, shell,
                      gnuplot
                  plugin_languages_sections: recently-used
                  plugin_languages_details: bytes-size, percentage
                  plugin_languages_limit: 4
