name: Metrics
on:
    schedule: [{ cron: '* * * * *' }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ['output'] }
jobs:
    metrics:
        runs-on: ubuntu-latest
        steps:
            - name: generate notable
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@v3.28
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update notable'
                  target_branch: output
                  filename: metrics.plugin.notable.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  user: minhtran241
                  base: ''
                  plugin_notable: yes
                  plugin_notable_from: all
                  plugin_notable_self: yes
                  plugin_notable_types: commit

            - name: generate isocalendar
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@v3.28
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update isocalendar'
                  target_branch: output
                  filename: metrics.plugin.isocalendar.halfyear.svg
                  base: ''
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: half-year
                  token: ${{ secrets.GITHUB_TOKEN }}
                  user: minhtran241

            - name: generate classics
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@latest
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update classics'
                  target_branch: output
                  filename: metrics.classic.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  user: minhtran241
                  base: header, repositories
                  plugin_lines: yes

            - name: generate recent languages
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@latest
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update recent languages'
                  target_branch: output
                  filename: metrics.plugin.languages.recent.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  user: minhtran241
                  base: ''
                  plugin_languages: yes
                  plugin_languages_ignored: >-
                      html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
                      gnuplot
                  plugin_languages_sections: recently-used
                  plugin_languages_details: bytes-size, percentage
                  plugin_languages_limit: 4

            - name: generate pinned repos
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@latest
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update pinned repos'
                  target_branch: output
                  filename: metrics.plugin.repositories.pinned.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  user: minhtran241
                  base: ''
                  plugin_repositories: yes
                  plugin_repositories_pinned: 4

            - name: generate habits charts
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@latest
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update habits charts'
                  target_branch: output
                  filename: metrics.plugin.habits.charts.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  user: minhtran241
                  base: ''
                  plugin_habits: yes
                  plugin_habits_facts: no
                  plugin_habits_charts: yes
                  config_timezone: America/Detroit
