name: Most Used
on:
    # Schedule updates (each hour)
    schedule: [{ cron: '0 * * * *' }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ['output'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@v3.28
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update metrics'
                  filename: metrics.plugin.languages.details.svg
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: ''
                  plugin_languages: ye
                  plugin_languages_details: bytes-size, percentage
                  plugin_languages_limit: 10
                  plugin_languages_analysis_timeout: 15
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_ignored: html, css, pug, less, dockerfile, makefile, Handlebars, Procfile, qmake, lex, cmake, shell,  gnuplot
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%
