name: Snake
on:
    # Schedule updates (each hour)
    schedule: [{ cron: '0 * * * *' }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ['output'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: Platane/snk@master
              id: snake-gif

              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update metrics'
                  github_user_name: minhtran241
                  svg_out_path: dist/github-contribution-grid-snake.svg
            - uses: crazy-max/ghaction-github-pages@v2.1.3
              with:
                  output_action: commit
                  committer_branch: output
                  committer_message: 'update metrics'
                  target_branch: output
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
